package com.jarrm5.constant;

public enum ErrorReason {
	USER_BANNED,
	INBOX_FULL,
	BUDDY_LIST_FULL,
	DUPLICATE_BUDDY,
	MESSAGE_LENGTH_EXCEEDED,
	LOGIN_FAILED_PASSWORD,
	LOGIN_FAILED_ACCOUNT_LOCKED,
	USER_ACCOUNT_BANNED,
	USER_ACCOUNT_UNBANNED;
}
